"use client";
import { Activity, ArrowUpRight, Check, CheckCircle2, Circle, CircleDot, FilePlus2, FileText, FolderOpen, Gauge, ListChecks, PanelRightClose, Settings2, ShieldCheck, SlidersHorizontal } from "lucide-react";
import type { AgentConfig, EventType, PublicConfig, Session, WorkspaceFile } from "@/lib/types";
import { PRESETS } from "@/lib/settings";
import { formatBytes, formatCount, IconButton, shortTime, Spinner } from "./ui";

export type InspectorTab = "run" | "files" | "events";
const eventLabels: Record<EventType, string> = {
  "run.started": "Run started", "run.resumed": "Run resumed", "run.completed": "Run completed", "run.cancelled": "Run stopped", "run.failed": "Run failed", "run.interrupted": "Run interrupted",
  "message.user": "Message received", "message.assistant": "Response saved", "step.started": "Model step started", "tool.called": "Tool requested", "tool.completed": "Tool completed", "tool.failed": "Tool not completed",
  "approval.requested": "Approval requested", "approval.decided": "Approval answered", "plan.updated": "Plan updated", "todo.updated": "Todos updated", "goal.updated": "Goal updated", "ptc.started": "PTC started", "ptc.log": "PTC log", "ptc.completed": "PTC completed", "context.compacted": "Context compacted", "context.prepared": "Context prepared", "skills.loaded": "Skills loaded", "delegation.started": "Delegation started", "delegation.completed": "Delegation completed", "delegation.failed": "Delegation failed", "file.added": "File added", "session.forked": "Session forked",
};

interface Props {
  session: Session | null; config: AgentConfig; publicConfig: PublicConfig | null;
  tab: InspectorTab; onTab: (tab: InspectorTab) => void; onClose: () => void; onSettings: () => void;
  files: WorkspaceFile[]; filesLoading: boolean; filesLocked: boolean; onAddFile: () => void; onFile: (path: string) => void;
}

export function Inspector({ session, config, publicConfig, tab, onTab, onClose, onSettings, files, filesLoading, filesLocked, onAddFile, onFile }: Props) {
  const provider = publicConfig?.providers.find((item) => item.id === config.provider);
  return <aside className="inspector" aria-label="Session inspector"><div className="inspector-heading"><span>Under the hood</span><IconButton label="Close inspector" onClick={onClose}><PanelRightClose size={16} /></IconButton></div>
    <div className="inspector-tabs" role="tablist" aria-label="Inspector panels">{([ ["run", "Overview", SlidersHorizontal], ["files", "Files", FolderOpen], ["events", "Events", Activity] ] as const).map(([id, label, Icon]) => <button role="tab" key={id} aria-selected={tab === id} aria-controls={`inspector-${id}`} id={`tab-${id}`} className={tab === id ? "active" : ""} onClick={() => onTab(id)}><Icon size={13} />{label}{id === "files" && files.length > 0 && <span className="tab-count">{files.length}</span>}</button>)}</div>
    <div className="inspector-content" id={`inspector-${tab}`} role="tabpanel" aria-labelledby={`tab-${tab}`}>
      {tab === "run" && <>
        <section className="inspector-section"><div className="section-heading"><h2>YOUR AGENT</h2><button className="subtle-action" onClick={onSettings} aria-label="Edit agent settings"><Settings2 size={13} />Configure</button></div>
          <button className="agent-card" onClick={onSettings}><span className="agent-card-symbol"><span /><span /><span /></span><span><strong>{PRESETS[config.preset].label}</strong><small>{config.provider === "demo" ? "Demo adapter" : "DeepSeek adapter"}</small></span><ArrowUpRight size={15} /></button>
          <div className="model-line"><span>Model</span><code>{config.model}</code></div><div className="model-line"><span>Tool mode</span><strong>{config.toolMode ?? "native"}</strong></div><div className="model-line"><span>Connection</span><span className={`connection-state ${provider?.configured ? "" : "warning"}`}><i />{provider?.configured ? config.provider === "demo" ? "Local · key-free" : "Key configured" : "API key needed"}</span></div>
        </section>
        <section className="inspector-section"><div className="section-heading"><h2>CAPABILITIES</h2><span className="soft-counter">{config.tools.length} enabled</span></div><div className="capability-list">{publicConfig?.tools.filter(tool => tool.name !== "run_code").map((tool) => <div key={tool.name} className={`capability ${config.tools.includes(tool.name) ? "" : "disabled"}`}><span className="capability-check">{config.tools.includes(tool.name) ? <Check size={11} /> : <span />}</span><span>{tool.label}</span>{tool.approvalRequired ? <span className="approval-indicator" title="Always requires approval"><ShieldCheck size={13} /></span> : <span className="capability-detail">{tool.name === "update_plan" ? "Planning" : "Read-only"}</span>}</div>)}</div><p className="capability-caption"><ShieldCheck size={12} />Writes always ask first.</p></section>
        <section className="inspector-section"><div className="section-heading"><h2>THE PLAN</h2><ListChecks size={14} /></div>{session?.plan.length ? <ol className="plan-list">{session.plan.map((item) => <li key={item.id} className={item.status}>{item.status === "completed" ? <CheckCircle2 size={16} /> : item.status === "in_progress" ? <CircleDot size={16} /> : <Circle size={16} />}<span>{item.text}</span></li>)}</ol> : <div className="empty-plan"><ListChecks size={19} /><p>A little direction goes a long way.</p><span>Your agent’s plan will appear here.</span></div>}</section>
        {(session?.goal || session?.todos?.length) && <section className="inspector-section"><div className="section-heading"><h2>GOAL & TODOS</h2><ListChecks size={14} /></div>{session.goal && <p className="inspector-description"><strong>{session.goal.status === "completed" ? "Completed: " : "Goal: "}</strong>{session.goal.objective}</p>}{session.todos?.map(item => <div className="model-line" key={item.id}><span>{item.status}</span><span>{item.text}</span></div>)}</section>}
        <section className="inspector-section"><div className="section-heading"><h2>EXECUTION BUDGET</h2><Gauge size={14} /></div><div className="budget-grid"><div><span>Model steps</span><strong>{session?.run?.step ?? 0}<small> / {config.maxSteps}</small></strong><i><b style={{ width: `${Math.min(100, (session?.run?.step ?? 0) / config.maxSteps * 100)}%` }} /></i></div><div><span>Output limit / step</span><strong>{formatCount(config.maxTokens)}<small> tokens</small></strong><span className="budget-caption">Bounded by design</span></div></div>{session && session.usage.inputTokens + session.usage.outputTokens > 0 && <div className="usage-line"><span>{session.usage.estimated ? "Estimated token usage" : "Provider token usage"}</span><strong>{formatCount(session.usage.inputTokens + session.usage.outputTokens)}</strong></div>}</section>
      </>}
      {tab === "files" && <section className="inspector-section files-section"><div className="section-heading"><h2>SESSION WORKSPACE</h2><span className="soft-counter">{files.length} files</span></div><p className="inspector-description">A small, isolated home for this session’s files. Text files up to 64 KB.</p><button className="button secondary add-file-button" disabled={filesLocked} onClick={onAddFile}><FilePlus2 size={15} />Add file</button>{filesLoading ? <div className="panel-loading"><Spinner label="Loading files" /></div> : files.length ? <div className="file-list">{files.map((file) => <button key={file.path} className="file-row" onClick={() => onFile(file.path)}><span className="file-type-icon"><FileText size={16} /></span><span><strong>{file.path}</strong><small>{formatBytes(file.bytes)} · {shortTime(file.updatedAt)}</small></span><ArrowUpRight size={14} /></button>)}</div> : <div className="panel-empty"><FolderOpen size={29} strokeWidth={1.3} /><h3>Room for your ideas.</h3><p>Add a file, or ask your agent to prepare a draft.</p></div>}{filesLocked && <p className="inspector-description">Stop the current run before adding or replacing files manually.</p>}</section>}
      {tab === "events" && <section className="inspector-section"><div className="section-heading"><h2>EVENT HISTORY</h2><span className="soft-counter">{session?.events.length ?? 0}</span></div><p className="inspector-description">Every settled step, recorded in order. Nothing hidden behind a spinner.</p>{session?.events.length ? <div className="event-list">{[...session.events].reverse().map((event) => <details key={event.id} className={`event-row ${event.type.includes("failed") ? "event-error" : ""}`}><summary><i /><span><strong>{eventLabels[event.type]}</strong><small>#{event.seq} · {shortTime(event.timestamp)}</small></span><span className="event-expand">+</span></summary><pre>{JSON.stringify(event.data, null, 2)}</pre></details>)}</div> : <div className="panel-empty"><Activity size={29} strokeWidth={1.3} /><h3>A clear trail, from the start.</h3><p>Start a task to see model steps, tool results, and approval decisions.</p></div>}</section>}
    </div><div className="inspector-footer"><ShieldCheck size={17} /><div><strong>Safety is part of the workflow.</strong><span>Isolated files. Explicit approvals. No shell access.</span></div></div>
  </aside>;
}
